repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: [pydantic>=2.11.7, blessed>=1.20.0]
        args: [--ignore-missing-imports]
        files: ^src/

  # Note: pytest hook is commented out for faster pre-commit runs
  # Run manually with: uv run pytest --cov=src/term2ai --cov-report=term-missing
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: uv run pytest --cov=src/term2ai --cov-report=term-missing
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
